### ISSUE TITLE
[DOCUMENTATION] Create wiki home page and introduction

### ISSUE THREAD

**Issue by JacoMalan1** [CodeLog-Development/uncube#4]
## What needs to be done
The project probably needs a wiki. To start with, we need a title page with an introduction.

**Comment by luqmanalzobe** [comment]
Hey, do you have a discord or somewhere to contact you

**Comment by luqmanalzobe** [comment]
Hey, is there anywhere I can contact you? I'd like to contribute however this is my first contribution and I'd like to ask some questions

**Comment by luqmanalzobe** [comment]
I will be making a pull request, and made a homepage in HTML and CSS.

**Comment by JacoMalan1** [comment]
> Hey, is there anywhere I can contact you? I'd like to contribute however this is my first contribution and I'd like to ask some question

Of course. You can use my business email address to contact me jacom@codelog.co.za

**Comment by sahil-adit** [comment]
Hey can I help you for this project?This is my first project in open source contribution.

**Comment by JacoMalan1** [comment]
> Hey can I help you for this project?This is my first project in open source contribution.

Yes, of course. If you'd like to contribute, take a look at the issues that are currently open, try and solve one of them, and open a pull request to the `dev` branch.
If you need to contact me personally, you can use my business email: [jacom@codelog.co.za](mailto:jacom@codelog.co.za)

**Comment by code-Gambler** [comment]
I can work on this issue.

**Comment by ayuxy027** [comment]
Hey,
Assign this to me I can get this done

**Comment by ravixalgorithm** [comment]
is there anyone currently working on it?? if yes then please reply

**Comment by JacoMalan1** [comment]
> is there anyone currently working on it?? if yes then please reply

To my knowledge no one is working on this. Please feel free to work on it yourself. If you have anything you want to merge, just file a PR. I'm currently taking a break from developing this, but I would appreciate any help I can get.

**Comment by ravixalgorithm** [comment]
where can I find more details about uncube so that I can make a detailed one

**Comment by ravixalgorithm** [comment]
I had created the wiki pages {home and introduction page} @JacoMalan1

**Comment by JacoMalan1** [comment]
@ravixalgorithm I see that the home and introduction pages have been created. Thank you very much. I'm going to close this issue as being resolved now. I'll create a new issue for some of the other pages we might need.

**Comment by ravixalgorithm** [comment]
I would love to help, if needed
