### ISSUE TITLE
[Feature] Web application icon

### ISSUE THREAD

**Issue by JacoMalan1** [CodeLog-Development/uncube#85]
This project does not currently have an icon. We need one. The icon must conform to the PWA standards for icons so that it can be used as an application icon when a user installs the PWA.

**Comment by JacoMalan1** [comment]
For reference, here is [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons) on PWA icons.

**Comment by ravixalgorithm** [comment]
how to preview this project locally using yarn can you assist me??

**Comment by JacoMalan1** [comment]
> how to preview this project locally using yarn can you assist me??

@ravixalgorithm

First you need to install the dependencies, so in the root of the project directory, just use `yarn`.
You can run the frontend with `yarn nx serve webapp`
